name: macOS (arm64)

on: push

jobs:
  build:
    runs-on: macos-latest
    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-arm64
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
      - name: Build
        run: |
          xmake f -p macosx -a arm64 -m release
          xmake
      - name: Find shared libraries
        id: find_libraries
        run: |
          # Find only dylib files
          echo "LIBRARY_FILES=$(find build -type f -name "*.dylib" | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Upload shared libraries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.LIBRARY_FILES }}
